apiVersion: v1
kind: Pod
metadata:
  name: javahelloworld.example.com
  labels:
    app: helloworldjava
spec:
  containers:
  - name: simple-java
    image: prasanna23tunga/simple-java
    ports:
    - name: java-port
      containerPort: 3001
